services:
  elastic:
    extends:
      service: elastic
      file: ./elastic/docker-compose.yml

  es01:
    extends:
      service: es01
      file: ./es01/docker-compose.yml

  kibana:
    extends:
      service: kibana
      file: ./kibana/docker-compose.yml

volumes:
  certs:
    driver: local
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local
  kibanadata:
    driver: local